language: objective-c
osx_image: xcode9.0
xcode_project: DHSDK.xcodeproj
xcode_scheme: DHSDKTests
xcode_sdk: iphonesimulator9.3
env:
  global:
  - FRAMEWORK_NAME=DHSDK
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage bootstrap
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: Dv1qeFWwHrj5bZe+s/jSTuVkoRqEyDKZgG2TZemxJg+ivEbJL254ccbxygu6KV0gYiVW37KHGXIdZ/eTyb0W6XiCgDUnBzZ3LpjG6jknRODH06O3+qg922XDLq5IF221PjjrFslySEPeqcFfZE9lFaEhAVuj0TRPY9zyKTrESO+ykUj93ZHKiL2YbC2P6Tyh180OtJGoS0Ev9OZyVH7TQJM+i1iWYNu9dOLzeFrtC4rf2sZPyB9IZm07qEU/g4/BL7Vdb/tHgGf2zBubv1+fDCgGtMhaipdWHWw1vFUzRGag6BGsyWFvLRnpt1prB+9nl7D0l89uxUxZyNpSIa01eqooBAQ51mAZ7Get1eFZMvcMABjhBAD/3cENE0OBM7AoFdJhRsPA5IgiBCgn0lqY12AnP6sYmHo4XnFfJbI2StQW6DO3u54k08l4Y0UqNx7WshqNNaGqkOV3EH9fJx3QPOxkHUYLoOyFuYS99tvnzvrGPhv6e32yOIsCjHquByWvjvvjQP5t2oDIeQuhgD484TlG9iHNiFPnMv4RiGBq01sf/lc5BZWtTJibP8k+vef3Nz7J5RMsIdQlYBwuZ2TaF+Lu97LyzsoRzjkgfL3si9TPR1624HMVmf7OecnI5UZgy0f99bVUMnPeqxQhMZ94WC2fwENQVqQ6cx6GczyPz9A=
  file: DHSDK.framework.zip
  skip_cleanup: true
  on:
    repo: LeeDeokho/DHSDK
    tags: true
